# Generated by Django 3.2.8 on 2022-05-29 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('accounts', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('vat', models.PositiveIntegerField(unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.businessowner')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businessess',
                'ordering': ('vat',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('Κεντρικό Κατάστημα', 'Κεντρικό Κατάστημα'), ('Υποκατάστημα', 'Υποκατάστημα')], max_length=50, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('notify_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('address_number', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='checklists.activity')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='businesses.business')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='regions.region')),
                ('region_unity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='regions.regionunity')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='regions.state')),
                ('type_of_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='checklists.typeofactivity')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='regions.zipcode')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ('business__vat',),
            },
        ),
    ]
