# Generated by Django 3.1.2 on 2021-10-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='vat',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
