# Generated by Django 3.1.2 on 2021-10-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20211010_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ('vat',), 'verbose_name': 'Business', 'verbose_name_plural': 'Businessess'},
        ),
    ]
