# Generated by Django 3.1.2 on 2021-10-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20211010_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
