# Generated by Django 3.1.2 on 2021-10-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20211010_0019'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthregulator',
            name='branchstore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.store'),
        ),
    ]
