# Generated by Django 3.1.2 on 2021-10-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_healthregulator_branchstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthregulator',
            old_name='branchstore',
            new_name='store',
        ),
    ]
