# Generated by Django 3.1.2 on 2021-10-13 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_auto_20211013_0143'),
        ('accounts', '0003_auto_20211010_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthregulator',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthregulator', to='businesses.store'),
        ),
    ]
