# Generated by Django 3.2.8 on 2022-05-29 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Inspection unique identifier')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.inspector', verbose_name='Inspector')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='businesses.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completed', models.DateTimeField(auto_now_add=True, verbose_name='Complete date')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspection', verbose_name='Inspection')),
            ],
            options={
                'verbose_name': 'Completed',
                'verbose_name_plural': 'Completed',
                'ordering': ('-completed',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Choice')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timpestamp')),
                ('comment', models.TextField(blank=True, default='-', verbose_name='Comment')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='inspections.inspection', verbose_name='Inspection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklists.question', verbose_name='Checklist Item')),
            ],
        ),
    ]
