# Generated by Django 3.1.2 on 2021-10-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField(verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField(verbose_name='Display order')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='checklists.activity')),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='TypeOfActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_activities', to='checklists.activity')),
            ],
            options={
                'verbose_name': 'Type of Activity',
                'verbose_name_plural': 'Type of Activities',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='Description')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is Important')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Display order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='checklists.category', verbose_name='Category')),
                ('choices', models.ManyToManyField(to='checklists.Choice')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['order'],
            },
        ),
    ]
