# Generated by Django 3.1.2 on 2021-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
