# Generated by Django 3.1.2 on 2021-10-10 01:04

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20211010_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
    ]
